version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: nostr_user
      POSTGRES_PASSWORD: nostr_password
      POSTGRES_DB: nostr_relay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nostr_user -d nostr_relay"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
