version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nostr_relay_postgres
    environment:
      POSTGRES_USER: nostr_user
      POSTGRES_PASSWORD: nostr_password
      POSTGRES_DB: nostr_relay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nostr_user -d nostr_relay"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: nostr_relay_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
