name: Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Format and lint check
        run: |
          npm run format:check
          npm run lint:check

      - name: Build
        run: npm run build

      - name: Unit testing
        run: npm run test:cov
        env:
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: node-${{ matrix.node-version }}
          parallel: true

  finish:
    needs: check
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: 'node-18.x,node-20.x,node-21.x'
